### ISSUE TITLE
Erro na função

### ISSUE THREAD

**Issue by joaobnetto** [AlexandreDemarchiBR/T3D#7]
while(!feof(arquivo_entrada)) {
        if(i == 3) break;
         fscanf(arquivo_entrada, " %c", &comando);
        if(comando == 'T') {
            fscanf(arquivo_entrada, "%lf %lf %lf", &x, &y, &z);
            M = Trans(M, x, y, z);
        }
        else if (comando == 'R') {
            fscanf(arquivo_entrada, " %c %lf", &eixo, &graus);
            M = Rot(M, eixo, graus);
        }
        else if (comando == 'S') {
            fscanf(arquivo_entrada, "%lf %lf %lf", &x, &y, &z);
            M = Escala(M, x, y, z);
        }
        printf("%c %i\n",comando, i++);
    }

Essa função aqui lê uma vez a mais que o necessario, causando erro no resultado final. Se ela rodar o tempo certo, nao tem erro

**Comment by AlexandreDemarchiBR** [comment]
Voi dar uma olhada.
Também falta uma função pra destruir a lista

2017-11-28 17:48 GMT-02:00 joaobnetto <notifications@github.com>:

**Comment by AlexandreDemarchiBR** [comment]
O que acontecia é que o arquivo pode ter um caractere de nova linha antes
do EOF.
Modifiquei as entradas e parece estar correto agora.

2017-11-28 17:52 GMT-02:00 Milton Alexandre Souza Demarchi <
alexandre.demarchi1@gmail.com>:

**Comment by AlexandreDemarchiBR** [comment]
Resolvido
